name: build
on: [push]
jobs:
  maven:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        cache: 'maven'
        distribution: 'temurin'
    - name: compile
      run: mvn compile
  manual:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        cache: 'maven'
        distribution: 'temurin'
    - name: Download checkerframework
      run: curl 'https://checkerframework.org/checker-framework-3.43.0.zip' -o checkerframework.zip
    - name: unzip checkerframework
      run: unzip checkerframework.zip
    - name: compile
      run: time ./checker-framework-3.43.0/checker/bin/javac -processor nullness src/main/java/io/github/danthe1st/checkertest/TestClass.java